name: Tangle Config files

on:
  push:
    branches-ignore:
      - "main"

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tangle: yes
